# Generated by Django 4.0.3 on 2022-03-26 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombrePropiedad', models.CharField(max_length=40, null=True)),
                ('tipoPropiedad', models.CharField(choices=[('Cas', 'Casa'), ('Dep', 'Departamento'), ('Vil', 'Villa'), ('Res', 'Residencia'), ('Ofi', 'Oficina'), ('Ter', 'Terreno'), ('Bod', 'Bodega'), ('Des', 'Desarrollo'), ('Edi', 'Edificio')], default='Casa', max_length=12)),
                ('tipOperacion', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta')], default='V', max_length=5)),
                ('tipoAmenidades', models.TextField(choices=[('AC', 'Aire Acondicionado'), ('CCTV', 'Camaras de Seguridad'), ('Security', 'Seguridad privada'), ('Tenis', 'Cancha de tenis'), ('Futbol', 'Cancha de fútbol'), ('Terraza', 'Terraza'), ('Alberca', 'Alberca'), ('Jacuzzi', 'Jacuzzi'), ('internet', 'WiFi'), ('Cocina', 'Cocina Integral'), ('Aljibe', 'Aljibe'), ('Vista', 'Vista al Mar'), ('GYM', 'Gimnasio'), ('AreasVerdes', 'Áreas Verdes')], max_length=25)),
                ('descripcion', models.TextField(max_length=2000)),
                ('ubicacion', models.CharField(max_length=35)),
                ('costo', models.SlugField(max_length=255)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('estacionamientos', models.IntegerField(default=0)),
                ('metrosTerreno', models.IntegerField(default=0)),
                ('metrosConstruccion', models.IntegerField(default=0)),
                ('pisos', models.IntegerField(blank=True)),
            ],
        ),
    ]
